with first_version as ( 
    SELECT dbt_scd_id, 
            vendor_id,
            account_number,
            vendor_name,
            credit_rating,
            preferred_vendor_status,
            active_flag,
            purchasing_web_service_url,
            contact_type,
            row_nr_contact,
            title,
            fisrt_name,
            middle_name,
            last_name,
            suffix,
            phone_number,
            phone_number_type,
            email_address,
            address_type,
            address_line1,
            address_line2,
            city,
            state_province_name,
            postal_code,
            country_region_name,
            dbt_valid_from,
            dbt_valid_to,
            dbt_updated_at,
            row_number() over(partition by vendor_id order by dbt_valid_from) as row_nr
    FROM {{ ref('sp_vendor') }}
)
SELECT dbt_scd_id as sk_shipment,
       vendor_id,
       account_number,
       vendor_name,
       credit_rating,
       preferred_vendor_status,
       active_flag,
       purchasing_web_service_url,
       contact_type,
       row_nr_contact,
       title,
       fisrt_name,
       middle_name,
       last_name,
       suffix,
       phone_number,
       phone_number_type,
       email_address,
       address_type,
       address_line1,
       address_line2,
       city,
       state_province_name,
       postal_code,
       country_region_name,
       case
           when row_nr = 1 then '1970-01-01'
           else dbt_valid_from
       end as valid_from,
       coalesce(dbt_valid_to, '2200-01-01') as valid_to,
       dbt_updated_at as last_updated_at
from first_version