version: 2

models:
  - name: dim_date_model
    description: Date dimension table

  - name: dim_employee
    description: |
      Dimension table containing information about employees.
    columns:
      - name: sk_employee
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: employee_id
        description: The unique identifier for the employee.
        tests:
          - not_null
      - name: national_id_number
        description: The national ID number of the employee.
      - name: log_in_id
        description: The login ID of the employee.
      - name: job_title
        description: The job title of the employee.
      - name: birth_date
        description: The birth date of the employee.
      - name: marital_status
        description: The marital status of the employee.
      - name: gender
        description: The gender of the employee.
      - name: hire_date
        description: The hire date of the employee.
      - name: salaried_flag
        description: A flag indicating if the employee is salaried.
      - name: vacation_hours
        description: The number of vacation hours for the employee.
      - name: sick_leave_hours
        description: The number of sick leave hours for the employee.
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."

  - name: dim_vendor
    description: |
      Dimension table containing information about vendors.
    columns:
      - name: sk_vendor
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: vendor_id
        description: The unique identifier for the employee.
        tests:
          - not_null
      - name: account_number
        description: The account number of the vendor.
      - name: vendor_name
        description: The name of the vendor.
      - name: credit_rating
        description: The credit rating of the vendor.
      - name: preferred_vendor_status
        description: A flag indicating if the vendor is a preferred vendor.
      - name: active_flag
        description: A flag indicating if the vendor is active.
      - name: purchasing_web_service_url
        description: The URL of the purchasing web service for the vendor.
      - name: contact_type
        description: The type of contact for the vendor.
      - name: title
        description: The title of the contact person.
      - name: first_name
        description: The first name of the contact person.
      - name: middle_name
        description: The middle name of the contact person.
      - name: last_name
        description: The last name of the contact person.
      - name: suffix
        description: The suffix of the contact person.
      - name: phone_number
        description: The phone number of the contact person.
      - name: phone_number_type
        description: The type of phone number for the contact person.
      - name: email_address
        description: The email address of the contact person.
      - name: address_type
        description: The type of address for the vendor.
      - name: address_line1
        description: The first line of the address for the vendor.
      - name: address_line2
        description: The second line of the address for the vendor.
      - name: city
        description: The city of the address for the vendor.
      - name: state_province_name
        description: The state or province name of the address for the vendor.
      - name: postal_code
        description: The postal code of the address for the vendor.
      - name: country_region_name
        description: The country or region name of the address for the vendor.
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."       

  - name: dim_shipment
    description: |
      Dimension table containing information about shipment methods.
    columns:
      - name: sk_employee
        description: "A unique identifier for this record in the table"
        tests:
          - unique
          - not_null
      - name: ship_method_id
        description: The unique identifier for the shipment method.
        tests:
          - not_null
      - name: ship_name
        description: The name of the shipment method.
      - name: ship_base
        description: The base cost of the shipment.
      - name: ship_rate
        description: The rate of the shipment.
      - name: valid_from
        description: "This record is valid since this datetime."
      - name: valid_to
        description: "This record is valid until this datetime."
      - name: last_updated_at
        description: "Timestamp of the last update to this record."